### ISSUE TITLE
Is there a way to know which pixel or area in the image corresponding to the dominant colors?

### ISSUE THREAD

**Issue by springlo** [skt7/dominant-colors-in-an-image-using-k-means-clustering#1]

**Comment by skt7** [comment]
Yes, can be done by assigning cluster colors to the pixels as per their corresponding label value. To meet the same I have added a function colorPixels to the main DominantColors class at [#LL9 ](https://github.com/skt7/dominant-colors-in-an-image-using-k-means-clustering/blob/master/dominantColors.py#L99)

Also, have added a sample code [colorPixels.py](https://github.com/skt7/dominant-colors-in-an-image-using-k-means-clustering/blob/master/colorPixels.py) for your reference.
